// Builds the simulated "published" version of the fictional Skyline Charters web container.
// The drift watch serves this digest for GTM-SKY7Q2L so the sample shows realistic drift
// without calling Google (the sample container does not exist there).
const fs = require('fs'), D = require('../src/drift.js');
const cv = JSON.parse(fs.readFileSync(__dirname + '/sample-web.json', 'utf8')).containerVersion;
const live = JSON.parse(JSON.stringify(cv));
live.containerVersionId = '43';
live.tag.find(t => t.tagId === '25').paused = true;                       // Hotjar paused
live.tag = live.tag.filter(t => t.tagId !== '15');                          // Google Ads remarketing removed
live.tag.find(t => t.tagId === '12').firingTriggerId = ['23'];              // Meta Lead now fires on quote_requested
live.tag.push({ tagId: '28', name: 'Reddit Pixel', type: 'html', firingTriggerId: ['2147479553'],
  parameter: [{ type: 'TEMPLATE', key: 'html', value: '<script>rdt("init","t2_skyln");rdt("track","PageVisit");</script>' }] });
const ga4 = live.tag.find(t => t.tagId === '3');
ga4.parameter.push({ type: 'TEMPLATE', key: 'measurementIdOverride', value: 'G-NEWPROP77X' });
ga4.parameter = ga4.parameter.filter((p, i, a) => !(p.key === 'measurementIdOverride' && p.value !== 'G-NEWPROP77X'));
const digest = D.fromExport(live);
fs.writeFileSync(__dirname + '/../worker/src/demo.js', '// Generated by fixtures/make-demo.cjs. Fictional data.\nexport const DEMO = ' + JSON.stringify({ 'GTM-SKY7Q2L': digest }) + ';\n');
const base = D.fromExport(cv), names = {}; cv.tag.forEach(t => { names[t.tagId] = t.name; });
console.log(D.compare(base, digest, names).map(c => c.severity + ' ' + c.message).join('\n'));
