const fs=require('fs'),vm=require('vm');
const ctx={console,URL,Math,JSON,Date};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../src/gtm-auto.js','utf8')+'\n;globalThis.GTM_AUTO=GTM_AUTO;',ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../src/engine.js','utf8')+'\n;globalThis.GTM_ENGINE=GTM_ENGINE;',ctx);
const E=ctx.GTM_ENGINE;
const w=E.parseExport(fs.readFileSync(__dirname+'/../fixtures/sample-web.json','utf8'));
const s=E.parseExport(fs.readFileSync(__dirname+'/../fixtures/sample-server.json','utf8'));
console.log(w.info, s.info.context);
console.log('site', JSON.stringify(E.detectWebsite(w.cv,s.cv)));
const D=E.build({web:w,server:s,website:'skylinecharters.com'});
for(const c of D.containers) console.log(c.meta.publicId,c.score,JSON.stringify(c.dims),c.nodes.length,c.edges.length);
const R=D.report; console.log('counts',R.counts);
for(const i of R.items) console.log(i.severity.padEnd(8),i.container.padEnd(12),i.check.padEnd(11),i.name,'::',i.message.slice(0,110));
console.log('NOTES');for(const g of R.notes) console.log(g.count,g.container,g.message.slice(0,90),g.examples.join(', '));
console.log('FLOW',JSON.stringify(R.flow.summary));for(const r of R.flow.routes) console.log(r.status.padEnd(12),r.tag,'|',r.event,'|',r.client,'|',r.tags.join(', '),'|',r.reason);
fs.writeFileSync(__dirname+'/D.json',JSON.stringify(D));
const {jsPDF}=require('jspdf'); require('jspdf-autotable');
const REP=require('../src/report.js');
fs.writeFileSync(__dirname+'/out.md',REP.markdown(D.report));
fs.writeFileSync(__dirname+'/out.pdf',Buffer.from(REP.pdf(D.report,jsPDF)));
console.log('wrote', REP.fileBase(D.report));
