import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {evaluate,compare,parseContainer,parseSnapshot} from '../src/connected.ts';
import {evaluateGtmSignalQuality} from '../evals/eval_gtm_signal_quality.ts';
const fixture=JSON.parse(await readFile(new URL('./fixtures/container.json',import.meta.url),'utf8'));
const copy=()=>structuredClone(fixture);
test('original evaluator wrapper and hosted evaluator agree, repeatably without mutation',()=>{const c=copy(),raw=JSON.stringify(c);assert.deepEqual(evaluate(c),evaluateGtmSignalQuality(c));assert.deepEqual(evaluate(c),evaluate(c));assert.equal(JSON.stringify(c),raw);});
test('higher naming score is staged, not applied; target and deleted entities rejected',()=>{const candidate=copy();candidate.containerVersion.tag[0].name='GA4 - purchase';const r=compare(fixture,candidate);assert.equal(r.status,'eligible-for-review');assert.equal(r.applied,false);assert.equal(r.published,false);assert.equal(fixture.containerVersion.tag[0].name,'purchase tag');candidate.containerVersion.containerId='999';assert.equal(compare(fixture,candidate).eligible,false);candidate.containerVersion.containerId='200';candidate.containerVersion.tag=[];assert.equal(compare(fixture,candidate).eligible,false);});
test('same input has no improvement; individual dimension regression and new missing refs block',()=>{assert.equal(compare(fixture,fixture).status,'no-improvement');const candidate=copy();candidate.containerVersion.tag[0].name='GA4 - purchase';candidate.containerVersion.tag[0].firingTriggerId=['missing'];assert.equal(compare(fixture,candidate).eligible,false);const removed=copy();removed.containerVersion.trigger=[];assert.equal(compare(fixture,removed).eligible,false);const regression=copy();regression.containerVersion.trigger[0].name='bad';assert.ok(compare(fixture,regression).regressions.length);});
test('malformed exports and partial/nonfinite snapshots rejected before scoring',()=>{for(const c of [{}, {...fixture,containerVersion:{...fixture.containerVersion,folder:undefined}}, {...fixture,containerVersion:{...fixture.containerVersion,tag:[null]}}, {...fixture,containerVersion:{...fixture.containerVersion,tag:[fixture.containerVersion.tag[0],fixture.containerVersion.tag[0]]}}])assert.throws(()=>parseContainer(c));assert.throws(()=>parseSnapshot({generated_at:'2026-09-09T00:00:00Z',partial:true,funnel:[]}));assert.throws(()=>parseSnapshot({generated_at:'2026-09-09T00:00:00Z',funnel:[{from_event:'a',to_event:'b',ratio:Infinity,expected_low:0,expected_high:1,status:'high'}]}));const deep:any={};let p=deep;for(let i=0;i<35;i++){p.a={};p=p.a;}assert.throws(()=>parseContainer({...fixture,deep}));});
test('unknown prototype-named events do not crash original evaluator',()=>{for(const event of ['constructor','toString','__proto__']){const snapshot={generated_at:'2026-09-09T00:00:00Z',meta:{account_id:'1',account_name:'Fixture',pixel_id:'2',currency:'USD',spend:0,date_range:{since:'2026-09-01',until:'2026-09-08'},conversion_events:[{event,count_7d_click:1,count_1d_click:1,count_1d_view:0,value_7d_click:1}]},funnel:[]};assert.ok(Number.isFinite(evaluate(fixture,snapshot).combinedScore));}});

const parity=JSON.parse(await readFile(new URL("./fixtures/pre-extraction-parity.json",import.meta.url),"utf8"));
test("pre-extraction golden parity across structural, Meta, Google and full profiles",()=>{for(const c of parity)assert.deepEqual(evaluate(fixture,c.snapshot),c.expected);});

test('prototype-named tag and Google categories are harmless unknown values',()=>{const c=copy();c.containerVersion.tag[0].type='constructor';c.containerVersion.variable=[{variableId:'1',name:'x',type:'constructor'}];assert.ok(Number.isFinite(evaluate(c).combinedScore));const snapshot=structuredClone(parity[2].snapshot);snapshot.google_ads.conversion_actions[0].category='constructor';assert.ok(Number.isFinite(evaluate(fixture,snapshot).combinedScore));});
