import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { evaluateGtmSignalQuality, type GtmContainer } from "../evals/eval_gtm_signal_quality.js";
import { buildEvidence, freezeSeedDefinition, PythonJevJudge } from "../scripts/jev-shadow.js";
import { replayReport, splitByGroup, assertGroupDisjoint, type DatasetRow } from "../scripts/jev-offline.js";
const worker=path.resolve("scripts/jev_worker.py");
async function evidence(frozen=freezeSeedDefinition()) {
  const base=JSON.parse(await readFile("content/gtm-templates/BLADE/seed/blade-web.json","utf8")) as GtmContainer;
  const scores=evaluateGtmSignalQuality(base);
  return buildEvidence({parentId:"p",baseline:base,candidate:base,operations:[],targetedIssue:"test",before:scores,after:{...scores,combinedScore:scores.combinedScore+0.01},validation:{valid:true,reason:"OK",changedEntityIds:{tag:[],trigger:[],variable:[],folder:[]}},qa:{status:"passed"},frozen});
}
test("real Python worker binds Unicode frozen manifest and validates both functions before calls",async()=>{const { hash, manifestHash, frozenDefinitionFromManifest }=await import("../scripts/jev-shadow.js");const dir=await mkdtemp(path.join(os.tmpdir(),"jev-worker-")),manifestPath=path.join(dir,"manifest.json"),calls=path.join(dir,"calls.txt"),definition={candidate:{model:"mock-model",note:"é"},backend:{provider:"mock-provider",model:"mock-model"},selected_columns:["x"],column_mode:"explicit"},spec={path:"x",definitionHash:hash(definition),provider:"mock-provider",model:"mock-model"};const manifest:any={definitionHash:"definition-seed",requestedModel:"mock-model",preprocessingVersion:"v1",policyVersion:"p1",functions:{evidenceSufficient:spec,trackingBehaviorPreserved:{...spec,path:"y"}}};manifest.manifestHash=manifestHash(manifest);const e=await evidence(frozenDefinitionFromManifest(manifest));await writeFile(path.join(dir,"jev_align.py"),'import os\nclass Prediction:\n choice="pass"; confidence=0.8; probabilities={"pass":0.8}; resolved_model="mock-model"\nclass F:\n def __init__(self,path): self.path=path; self._definition='+JSON.stringify(definition)+'; self._state=object(); self._backend=object()\n def __call__(self,**kwargs): open(os.environ["CALLS"],"a").write(self.path); return Prediction()\nclass AIFunction:\n @staticmethod\n def load(path): return F(path)\n');await writeFile(manifestPath,JSON.stringify(manifest));const judge=new PythonJevJudge("python3",worker,manifestPath,1000,4096,{PYTHONPATH:dir,CALLS:calls});assert.equal((await judge.judge(e)).status,"success");assert.equal(await readFile(calls,"utf8"),"xy");await writeFile(calls,"");const tampered={...manifest,functions:{...manifest.functions,trackingBehaviorPreserved:{...manifest.functions.trackingBehaviorPreserved,model:"bad"}}};tampered.manifestHash=manifestHash(tampered);await writeFile(manifestPath,JSON.stringify(tampered));assert.equal((await judge.judge(e)).status,"error");assert.equal(await readFile(calls,"utf8"),"");});
test("offline report uses harmful and valid-fix denominators and keeps lineage groups intact",()=>{const row=(group:string,lineage:string,label:"pass"|"fail",route:"keep"|"review"|"revert"):DatasetRow & {route:typeof route}=>({input:{evidenceHash:group},prediction:{status:"unavailable",reason:"fake"},provenance:{containerGroup:group,lineageGroup:lineage,synthetic:true,samplingReasons:[]},label:{evidenceHash:group,trackingBehaviorPreserved:label,reviewer:"synthetic",reviewedAt:"now"},route});const rows=[row("a","one","fail","keep"),row("b","two","fail","review"),row("c","three","pass","revert"),row("d","four","pass","review")];const report=replayReport(rows);assert.equal(report.harmfulChangeApprovalRate,0.5);assert.equal(report.validFixRejectionRate,0.5);const linked=[row("A","shared","pass","review"),row("B","shared","pass","review"),row("B","other","pass","review")];const split=splitByGroup(linked),permuted=splitByGroup([...linked].reverse());assertGroupDisjoint(split);assert.equal(Object.values(split).filter(v=>v.length).length,1);assert.deepEqual(Object.values(split).map(v=>v.length),Object.values(permuted).map(v=>v.length));const repeated=splitByGroup([...linked,linked[0]]);assert.equal(Object.values(repeated).findIndex(v=>v.length===4),Object.values(split).findIndex(v=>v.length===3));});

test("frozen manifests require complete identity and create accepted run definitions",async()=>{const { frozenDefinitionFromManifest, manifestHash }=await import("../scripts/jev-shadow.js");assert.throws(()=>frozenDefinitionFromManifest({}));const raw:any={definitionHash:"abc",requestedModel:"model",preprocessingVersion:"v1",policyVersion:"p1",functions:{evidenceSufficient:{path:"a",definitionHash:"a",provider:"p",model:"m"},trackingBehaviorPreserved:{path:"b",definitionHash:"b",provider:"p",model:"m"}}};raw.manifestHash=manifestHash(raw);const frozen=frozenDefinitionFromManifest(raw);assert.equal(frozen.status,"seed");assert.equal(frozen.contentHash,raw.manifestHash);const e=await evidence(frozen);const { FakeJudge, shadowPolicy }=await import("../scripts/jev-shadow.js");assert.equal(shadowPolicy(e,await new FakeJudge().judge(e)).route,"review");});
