import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { evaluateGtmSignalQuality, type GtmContainer } from "../evals/eval_gtm_signal_quality.js";
import { buildEvidence, freezeSeedDefinition, PythonJevJudge } from "../scripts/jev-shadow.js";
import { replayReport, splitByGroup, assertGroupDisjoint, type DatasetRow } from "../scripts/jev-offline.js";
const worker=path.resolve("scripts/jev_worker.py");
async function evidence(){const base=JSON.parse(await readFile("content/gtm-templates/BLADE/seed/blade-web.json","utf8")) as GtmContainer;const scores=evaluateGtmSignalQuality(base);return buildEvidence({parentId:"p",baseline:base,candidate:base,operations:[],targetedIssue:"test",before:scores,after:{...scores,combinedScore:scores.combinedScore+0.01},validation:{valid:true,reason:"OK",changedEntityIds:{tag:[],trigger:[],variable:[],folder:[]}},qa:{status:"passed"},frozen:freezeSeedDefinition()});}
test("real Python worker normalizes mocked jev_align Prediction and verifies frozen sidecar",async()=>{const e=await evidence(),dir=await mkdtemp(path.join(os.tmpdir(),"jev-worker-")),definition=path.join(dir,"definition.json");await writeFile(definition,"{}");await writeFile(definition+".freeze.json",JSON.stringify({definitionHash:e.frozen.contentHash,requestedModel:e.frozen.requestedModel,preprocessingVersion:e.frozen.preprocessingVersion}));await writeFile(path.join(dir,"jev_align.py"),'class Prediction:\n choice={"evidenceSufficient":"pass","trackingBehaviorPreserved":"pass"}\n label_probabilities={"pass":0.8,"fail":0.2}\n model="mock-model"\nclass F:\n def __call__(self,**kwargs): return Prediction()\nclass AIFunction:\n @staticmethod\n def load(path): return F()\n');const result=await new PythonJevJudge("python3",worker,definition,1000,4096,{PYTHONPATH:dir}).judge(e);assert.equal(result.status,"success");if(result.status==="success")assert.ok(Math.abs((result.uncertainty ?? 0)-0.2)<1e-9);await writeFile(definition+".freeze.json","{}");assert.equal((await new PythonJevJudge("python3",worker,definition,1000,4096,{PYTHONPATH:dir}).judge(e)).status,"error");});
test("offline report uses harmful and valid-fix denominators and keeps lineage groups intact",()=>{const row=(group:string,lineage:string,label:"pass"|"fail",route:"keep"|"review"|"revert"):DatasetRow & {route:typeof route}=>({input:{evidenceHash:group},prediction:{status:"unavailable",reason:"fake"},provenance:{containerGroup:group,lineageGroup:lineage,synthetic:true,samplingReasons:[]},label:{evidenceHash:group,trackingBehaviorPreserved:label,reviewer:"synthetic",reviewedAt:"now"},route});const rows=[row("a","one","fail","keep"),row("b","two","fail","review"),row("c","three","pass","revert"),row("d","four","pass","review")];const report=replayReport(rows);assert.equal(report.harmfulChangeApprovalRate,0.5);assert.equal(report.validFixRejectionRate,0.5);const split=splitByGroup([row("same","L1","pass","review"),row("same","L2","pass","review")]);assertGroupDisjoint(split);});
