import assert from "node:assert/strict"; import test from "node:test"; import { readFile } from "node:fs/promises"; import type { GtmContainer } from "../evals/eval_gtm_signal_quality.js"; import { evaluateGtmSignalQuality } from "../evals/eval_gtm_signal_quality.js"; import { applyOperations, validateCandidate } from "../scripts/gtm-container-mutations.js"; import { buildEvidence, compactJudgeInput, FakeJudge, freezeSeedDefinition, hash, shadowPolicy, validateJudgeResult } from "../scripts/jev-shadow.js"; import { assertGroupDisjoint, splitByGroup } from "../scripts/jev-offline.js";
const fixture=async()=>JSON.parse(await readFile("content/gtm-templates/BLADE/seed/blade-web.json","utf8")) as GtmContainer;
test("evidence is stable, reconstructable, and excludes labels and legacy actions",async()=>{const base=await fixture();const tag=base.containerVersion.tag![0];const ops=[{op:"rename_tags" as const,renames:[{tagId:tag.tagId,newName:"Bing - All Pages"}]}];const candidate=applyOperations(base,ops);const before=evaluateGtmSignalQuality(base),after=evaluateGtmSignalQuality(candidate);const evidence=buildEvidence({runId:"run",parentId:"parent",candidateId:"candidate",baseline:base,candidate,operations:ops,targetedIssue:"name",before,after,validation:validateCandidate(base,candidate,ops),frozen:freezeSeedDefinition()});assert.equal(evidence.baselineHash,hash(base));assert.notEqual(evidence.baselineHash,evidence.candidateHash);const input=JSON.stringify(compactJudgeInput(evidence));assert.ok(!input.includes("legacy"));assert.ok(!input.includes("label"));assert.ok(!input.includes("<script>"));});
test("policy routes unavailable and missing QA to review and cannot overturn deterministic failure",async()=>{const base=await fixture();const ops=[{op:"rename_tags" as const,renames:[{tagId:base.containerVersion.tag![0].tagId,newName:"x"}]}];const candidate=applyOperations(base,ops),before=evaluateGtmSignalQuality(base),after=evaluateGtmSignalQuality(candidate);const evidence=buildEvidence({parentId:"p",baseline:base,candidate,operations:ops,targetedIssue:"x",before,after,validation:validateCandidate(base,candidate,ops)});const judge=await new FakeJudge().judge(evidence);assert.equal(shadowPolicy(evidence,judge).route,"review");const invalid={...evidence,validation:{valid:false,reason:"bad"},qa:{status:"passed" as const}};assert.equal(shadowPolicy(invalid,judge).route,"revert");assert.equal(validateJudgeResult({status:"success",evidenceHash:"wrong",definitionHash:"wrong",requestedModel:"x",answers:{evidenceSufficient:"pass",purchaseBehaviorPreserved:"pass"}},evidence).status,"error");});
test("group splits are deterministic and disjoint",async()=>{const base=await fixture(),scores=evaluateGtmSignalQuality(base);const e=buildEvidence({parentId:"same",baseline:base,candidate:base,operations:[],targetedIssue:"none",before:scores,after:scores,validation:{valid:true,reason:"OK",changedEntityIds:{tag:[],trigger:[],variable:[],folder:[]}}});const rows=[0,1,2,3,4].map(i=>({input:{evidenceHash:`${i}`},prediction:{status:"unavailable" as const,reason:"fake"},provenance:{containerGroup:`group-${i}`,lineageGroup:"same",synthetic:true,samplingReasons:["random-audit"]}}));const split=splitByGroup(rows);assertGroupDisjoint(split);assert.equal(split.train.length+split.validation.length+split.holdout.length,5);assert.ok(e.candidateHash);});

test("python adapter contains malformed, timeout, oversized, and identity failures",async()=>{const { PythonJevJudge }=await import("../scripts/jev-shadow.js");const base=await fixture(),scores=evaluateGtmSignalQuality(base);const evidence=buildEvidence({parentId:"p",baseline:base,candidate:base,operations:[],targetedIssue:"ok",before:scores,after:scores,validation:{valid:true,reason:"OK",changedEntityIds:{tag:[],trigger:[],variable:[],folder:[]}}});const worker="tests/fixtures/fake-jev-worker.py";assert.equal((await new PythonJevJudge("python3",worker,"fake",1000).judge(evidence)).status,"success");for(const issue of ["malformed","timeout","oversized","wrong"]){const result=await new PythonJevJudge("python3",worker,"fake",25,1024).judge({...evidence,targetedIssue:issue});assert.notEqual(result.status,"success");}});

test("synthetic lab adapter filters every observable stream at decision time without oracle input",async()=>{const { observeSyntheticCase }=await import("../scripts/synthetic-lab-adapter.js");const root="/Users/jordaaan/Documents/ChatGPT/Measure U/synthetic-gtm-lab";const observation=await observeSyntheticCase(root,"case-008","2026-01-02T06:00:00Z");assert.equal(observation.provenance.synthetic,true);assert.ok((observation.facts.visitorEvents as number)>0);assert.ok((observation.cautions as string[]).some(x=>x.includes("oracle")));assert.ok(JSON.stringify(observation).indexOf("ground-truth")===-1);});


test("synthetic replay rows preserve the whole shared seed lineage in one split",async()=>{const { buildSyntheticReplayRows }=await import("../scripts/synthetic-lab-adapter.js");const { splitByGroup,assertGroupDisjoint }=await import("../scripts/jev-offline.js");const rows=await buildSyntheticReplayRows("/Users/jordaaan/Documents/ChatGPT/Measure U/synthetic-gtm-lab","2026-01-02T06:00:00Z");const split=splitByGroup(rows);assertGroupDisjoint(split);assert.equal(rows.length,12);assert.equal(Object.values(split).filter(v=>v.length>0).length,1);assert.ok(!JSON.stringify(rows).includes("ground-truth"));});
