import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { evaluateGtmSignalQuality, type GtmContainer } from "../evals/eval_gtm_signal_quality.js";
import { buildEvidence, freezeSeedDefinition, PythonJevJudge } from "../scripts/jev-shadow.js";
import { replayReport, splitByGroup, assertGroupDisjoint, type DatasetRow } from "../scripts/jev-offline.js";
const worker=path.resolve("scripts/jev_worker.py");
async function evidence(){const base=JSON.parse(await readFile("content/gtm-templates/BLADE/seed/blade-web.json","utf8")) as GtmContainer;const scores=evaluateGtmSignalQuality(base);return buildEvidence({parentId:"p",baseline:base,candidate:base,operations:[],targetedIssue:"test",before:scores,after:{...scores,combinedScore:scores.combinedScore+0.01},validation:{valid:true,reason:"OK",changedEntityIds:{tag:[],trigger:[],variable:[],folder:[]}},qa:{status:"passed"},frozen:freezeSeedDefinition()});}
test("real Python worker normalizes two mocked atomic string-choice runs and verifies loaded identity",async()=>{const e=await evidence(),dir=await mkdtemp(path.join(os.tmpdir(),"jev-worker-")),manifest=path.join(dir,"manifest.json"),id="622adf2b85e673f3cf73720432553dd8c52b149a885a2e6baf1946b65df42f47";await writeFile(path.join(dir,"jev_align.py"),'class Prediction:\n def __init__(self,choice): self.choice=choice; self.label_probabilities={choice:0.8,"fail":0.2}\nclass F:\n def __init__(self,choice): self.choice=choice; self.current_candidate=None; self.backend=None; self.selected_columns=None; self.column_mode=None\n def __call__(self,**kwargs): return Prediction(self.choice)\nclass AIFunction:\n @staticmethod\n def load(path): return F("pass")\n');const spec={path:"x",loadedIdentityHash:id};await writeFile(manifest,JSON.stringify({definitionHash:e.frozen.contentHash,requestedModel:e.frozen.requestedModel,preprocessingVersion:e.frozen.preprocessingVersion,functions:{evidenceSufficient:spec,trackingBehaviorPreserved:spec}}));const result=await new PythonJevJudge("python3",worker,manifest,1000,4096,{PYTHONPATH:dir}).judge(e);assert.equal(result.status,"success");if(result.status==="success"){assert.equal(result.answers.trackingBehaviorPreserved,"pass");assert.ok(Math.abs((result.uncertainty??0)-0.2)<1e-9)}await writeFile(manifest,JSON.stringify({definitionHash:e.frozen.contentHash,requestedModel:e.frozen.requestedModel,preprocessingVersion:e.frozen.preprocessingVersion,functions:{evidenceSufficient:{...spec,loadedIdentityHash:"bad"},trackingBehaviorPreserved:spec}}));assert.equal((await new PythonJevJudge("python3",worker,manifest,1000,4096,{PYTHONPATH:dir}).judge(e)).status,"error");});
test("offline report uses harmful and valid-fix denominators and keeps lineage groups intact",()=>{const row=(group:string,lineage:string,label:"pass"|"fail",route:"keep"|"review"|"revert"):DatasetRow & {route:typeof route}=>({input:{evidenceHash:group},prediction:{status:"unavailable",reason:"fake"},provenance:{containerGroup:group,lineageGroup:lineage,synthetic:true,samplingReasons:[]},label:{evidenceHash:group,trackingBehaviorPreserved:label,reviewer:"synthetic",reviewedAt:"now"},route});const rows=[row("a","one","fail","keep"),row("b","two","fail","review"),row("c","three","pass","revert"),row("d","four","pass","review")];const report=replayReport(rows);assert.equal(report.harmfulChangeApprovalRate,0.5);assert.equal(report.validFixRejectionRate,0.5);const linked=[row("A","shared","pass","review"),row("B","shared","pass","review"),row("B","other","pass","review")];const split=splitByGroup(linked);assertGroupDisjoint(split);assert.equal(Object.values(split).filter(v=>v.length).length,1);});
