// Generated by build.py from src/scan.js. Edit that file, then run npm run build.
// Site scan. Three pure functions shared by the Worker and the page:
//   detect(html, url)                  what one page's source loads (Worker, per crawled page)
//   summarize(pages)                   roll the pages up into one site picture (Worker and page)
//   compare(summary, web, server, site) findings: the live site against the container export (page only;
//                                      the export never leaves the browser)
// Everything here reads page *source*. Tags that GTM injects at runtime are not in the source, by design:
// anything found here runs outside GTM.
var GTM_SCAN = (function () {
  'use strict';

  /* ---------- helpers ---------- */
  function hostOf(u) { try { return new URL(/^https?:/i.test(u) ? u : 'https://' + u).host.toLowerCase(); } catch (e) { return null; } }
  function rootDomain(h) {
    if (!h) return null; h = String(h).toLowerCase().replace(/^www\./, '').replace(/:\d+$/, '');
    var p = h.split('.'); if (p.length <= 2) return h;
    var two = p.slice(-2).join('.'); if (/^(co|com|org|net|gov|ac)\.[a-z]{2}$/.test(two)) return p.slice(-3).join('.');
    return two;
  }
  function uniq(a) { return a.filter(function (x, i) { return a.indexOf(x) === i; }); }
  function all(re, s, g) { var out = [], m; re.lastIndex = 0; while ((m = re.exec(s))) { out.push(m[g == null ? 1 : g]); if (!re.global) break; } return out; }
  var GOOGLE_HOST = /(^|\.)(googletagmanager|google-analytics|googleadservices|doubleclick|google)\.com$/;
  var SKIP_EXT = /\.(pdf|jpe?g|png|gif|webp|avif|svg|ico|zip|gz|mp4|mov|webm|mp3|wav|css|js|mjs|json|xml|txt|rss|atom|woff2?|ttf|eot|csv|xlsx?|docx?|pptx?)$/i;
  var TRACKING_PARAMS = /^(utm_|gclid|gbraid|wbraid|fbclid|ttclid|msclkid|li_fat_id|mc_|_ga|_gl|ref$|srsltid)/i;

  // A canonical URL for de-duplicating the crawl: no hash, no tracking parameters, no trailing slash except root.
  function normalize(u, base) {
    var x; try { x = new URL(u, base); } catch (e) { return null; }
    if (!/^https?:$/.test(x.protocol)) return null;
    x.hash = '';
    var keep = []; x.searchParams.forEach(function (v, k) { if (!TRACKING_PARAMS.test(k)) keep.push([k, v]); });
    x.search = ''; keep.sort().forEach(function (kv) { x.searchParams.append(kv[0], kv[1]); });
    if (x.pathname.length > 1) x.pathname = x.pathname.replace(/\/+$/, '');
    return x.toString();
  }
  function crawlable(u, site) {
    var h = hostOf(u); if (!h || rootDomain(h) !== site) return false;
    try { var p = new URL(u).pathname; return !SKIP_EXT.test(p) && !/\/(cart|checkout|account|login|logout|signin|signup|wp-admin|wp-login|admin)(\/|$)/i.test(p); } catch (e) { return false; }
  }

  /* ---------- robots.txt ---------- */
  function robots(text, agent) {
    var groups = [], cur = null, sitemaps = [];
    String(text || '').split(/\r?\n/).forEach(function (line) {
      line = line.replace(/#.*/, '').trim(); if (!line) return;
      var m = /^([a-z-]+)\s*:\s*(.*)$/i.exec(line); if (!m) return;
      var k = m[1].toLowerCase(), v = m[2].trim();
      if (k === 'sitemap') { sitemaps.push(v); return; }
      if (k === 'user-agent') { if (!cur || cur.rules.length) { cur = { agents: [], rules: [] }; groups.push(cur); } cur.agents.push(v.toLowerCase()); return; }
      if (cur && (k === 'disallow' || k === 'allow')) cur.rules.push([k, v]);
    });
    var mine = groups.filter(function (g) { return g.agents.some(function (a) { return a !== '*' && agent.toLowerCase().indexOf(a) >= 0; }); });
    var pick = mine.length ? mine : groups.filter(function (g) { return g.agents.indexOf('*') >= 0; });
    var rules = [].concat.apply([], pick.map(function (g) { return g.rules; })).filter(function (r) { return r[1] !== '' || r[0] === 'allow'; });
    return { rules: rules, sitemaps: sitemaps };
  }
  function allowed(rules, path) {
    var best = null;
    (rules || []).forEach(function (r) {
      var pat = r[1]; if (!pat) return;
      var re = new RegExp('^' + pat.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*').replace(/\\\$$/, '$'));
      if (re.test(path) && (!best || pat.length > best[1].length || (pat.length === best[1].length && r[0] === 'allow'))) best = r;
    });
    return !best || best[0] === 'allow';
  }
  function sitemapLocs(xml) { return all(/<loc>\s*([^<\s]+)\s*<\/loc>/gi, String(xml || '')).map(function (s) { return s.replace(/&amp;/g, '&'); }); }
  // Pick pages that cover different templates: the home page, then round-robin across first path segments.
  // The template a URL probably uses: its first path segment, skipping a locale prefix (/de/blog → blog).
  // Localised copies of a template come last, so a budget is spent on different page types first.
  var LOCALE = /^[a-z]{2}(?:[-_][a-z]{2,4})?$/i;
  function template(u) {
    var segs; try { segs = new URL(u).pathname.split('/').filter(Boolean); } catch (e) { return { key: '', localized: false }; }
    var loc = segs.length && LOCALE.test(segs[0]) && !/^(go|my|us|uk|ai|io|tv|faq|app|api)$/i.test(segs[0]);
    var rest = loc ? segs.slice(1) : segs;
    return { key: (rest[0] || '') + (rest.length > 1 ? '/*' : ''), localized: !!loc };
  }
  function sample(urls, max) {
    var groups = {}, order = [], later = [];
    urls.forEach(function (u) {
      var t = template(u); if (t.localized) { if (later.indexOf(u) < 0) later.push(u); return; }
      if (!groups[t.key]) { groups[t.key] = []; order.push(t.key); } if (groups[t.key].indexOf(u) < 0) groups[t.key].push(u);
    });
    var out = [], i = 0;
    while (out.length < max && order.some(function (s) { return groups[s].length > i; })) { order.forEach(function (s) { if (out.length < max && groups[s][i]) out.push(groups[s][i]); }); i++; }
    return out.concat(later.slice(0, Math.max(0, max - out.length)));
  }

  /* ---------- one page ---------- */
  var CMP = [[/cdn\.cookielaw\.org|otSDKStub|onetrust/i, 'OneTrust'], [/consent\.cookiebot\.com|cookiebot/i, 'Cookiebot'], [/usercentrics/i, 'Usercentrics'], [/app\.termly\.io|termly/i, 'Termly'], [/iubenda/i, 'iubenda'], [/cookieyes|cookie-law-info/i, 'CookieYes'], [/osano\.com/i, 'Osano'], [/didomi/i, 'Didomi'], [/trustarc|truste\.com/i, 'TrustArc'], [/cookiefirst/i, 'CookieFirst'], [/complianz/i, 'Complianz'], [/shopify.*customerPrivacy|privacy-banner/i, 'Shopify privacy banner']];
  var PLATFORM = [[/cdn\.shopify\.com|Shopify\.theme/i, 'Shopify'], [/\/wp-content\/|\/wp-includes\//i, 'WordPress'], [/webflow\.(com|io)|data-wf-page/i, 'Webflow'], [/static\.squarespace\.com|squarespace/i, 'Squarespace'], [/static\.wixstatic\.com|wix\.com/i, 'Wix'], [/__NEXT_DATA__|\/_next\/static\//, 'Next.js'], [/framerusercontent\.com|framer\.com\/m\//i, 'Framer'], [/hs-scripts\.com|hubspot/i, 'HubSpot'], [/__NUXT__/, 'Nuxt'], [/cdn\.bigcommerce\.com/i, 'BigCommerce']];
  // vendor pixels initialised in page source: [vendor, id regex on inline code, presence regex on src/inline]
  var PIXELS = [
    ['Meta', /fbq\(\s*['"]init['"]\s*,\s*['"]?(\d{8,20})/g, /connect\.facebook\.net\/[^'"]*fbevents\.js|fbq\(/],
    ['TikTok', /ttq\.load\(\s*['"]([A-Z0-9]{12,30})['"]/g, /analytics\.tiktok\.com|ttq\./],
    ['LinkedIn', /_linkedin_partner_id\s*=\s*["']?(\d{4,12})/g, /snap\.licdn\.com|_linkedin_partner_id/],
    ['Microsoft Ads', /\bti\s*:\s*["']?(\d{5,12})/g, /bat\.bing\.com/],
    ['Pinterest', /pintrk\(\s*['"]load['"]\s*,\s*['"](\d{8,16})/g, /s\.pinimg\.com\/ct|pintrk\(/],
    ['Snapchat', /snaptr\(\s*['"]init['"]\s*,\s*['"]([a-f0-9-]{20,40})/g, /sc-static\.net|snaptr\(/],
    ['Reddit', /rdt\(\s*['"]init['"]\s*,\s*['"]([a-z0-9_]{6,30})/gi, /redditstatic\.com|rdt\(/],
    ['X (Twitter)', /twq\(\s*['"](?:init|config)['"]\s*,\s*['"]([a-z0-9]{4,12})/gi, /static\.ads-twitter\.com|twq\(/],
    ['Hotjar', /hjid\s*:\s*(\d{5,10})/g, /static\.hotjar\.com|hjid/],
    ['Microsoft Clarity', /clarity\.ms\/tag\/["']?\s*\+?\s*["']?([a-z0-9]{6,12})|["']clarity["']\s*,\s*["']script["']\s*,\s*["']([a-z0-9]{6,12})/gi, /clarity\.ms\/tag/],
    ['Klaviyo', /klaviyo\.js\?company_id=([A-Za-z0-9]{4,10})/g, /static\.klaviyo\.com/],
    ['Segment', /analytics\.load\(\s*["']([A-Za-z0-9]{20,40})["']/g, /cdn\.segment\.com/],
  ];

  function detect(html, pageUrl) {
    html = String(html || '');
    var lower = html.toLowerCase(), headEnd = lower.indexOf('</head>'), out = {
      title: ((/<title[^>]*>([^<]{0,200})/i.exec(html) || [])[1] || '').replace(/\s+/g, ' ').trim(),
      bytes: html.length, inHead: headEnd >= 0,
      gtm: [], loaders: [], noscript: [], gtag: [], pixels: [], legacy: [], consent: { defaults: 0, updates: 0, cmp: [] },
      events: [], endpoints: [], platform: [], links: [], textChars: 0,
    };
    var scripts = [], re = /<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi, m;
    while ((m = re.exec(html))) {
      var src = (/\bsrc\s*=\s*["']([^"']+)["']/i.exec(m[1]) || [])[1] || '';
      scripts.push({ src: src.replace(/&amp;/g, '&'), body: m[2], at: m.index, head: headEnd >= 0 && m.index < headEnd });
    }
    var inline = scripts.map(function (s) { return s.body; }).join('\n;\n');
    var srcs = scripts.map(function (s) { return s.src; }).filter(Boolean);
    var abs = function (s) { try { return new URL(s, pageUrl).toString(); } catch (e) { return s; } };

    // GTM: by script src, by the standard snippet, or by a custom (first-party) loader
    scripts.forEach(function (s) {
      if (s.src) {
        var u = abs(s.src), h = hostOf(u), id = (/[?&]id=(GTM-[A-Z0-9]{4,12})/.exec(u) || [])[1];
        if (id && /\/gtm\.js/.test(u)) out.gtm.push({ id: id, via: 'src', host: h, head: s.head });
        return;
      }
      var b = s.body;
      if (!/gtm\.start|gtm\.js|googletagmanager\.com\/gtm/.test(b)) return;
      var ids = uniq(b.match(/GTM-[A-Z0-9]{4,12}/g) || []);
      var hosts = uniq(all(/(?:https?:)?\/\/([a-z0-9-]+(?:\.[a-z0-9-]+)+)\//gi, b).map(function (x) { return x.toLowerCase(); }));
      var g = hosts.filter(function (x) { return /googletagmanager\.com$/.test(x); })[0], custom = hosts.filter(function (x) { return !GOOGLE_HOST.test(x); })[0];
      var host = custom || g || 'www.googletagmanager.com';
      if (custom) out.loaders.push({ host: custom, ids: ids, head: s.head });
      ids.forEach(function (id) { out.gtm.push({ id: id, via: custom ? 'custom loader' : 'snippet', host: host, head: s.head }); });
      if (!ids.length && custom) out.gtm.push({ id: null, via: 'custom loader', host: custom, head: s.head });
    });
    out.noscript = uniq(all(/googletagmanager\.com\/ns\.html\?id=(GTM-[A-Z0-9]{4,12})/g, html).concat(all(/\/ns\.html\?id=(GTM-[A-Z0-9]{4,12})/g, html)));

    // gtag.js and direct Google IDs (outside GTM by definition: GTM-injected tags are not in the source)
    srcs.forEach(function (s) { var u = abs(s); var id = (/googletagmanager\.com\/gtag\/js\?[^"']*?id=((?:G|AW|GT|DC)-[A-Z0-9]{4,14})/.exec(u) || [])[1]; if (id) out.gtag.push({ id: id, via: 'gtag.js' }); });
    all(/gtag\(\s*['"]config['"]\s*,\s*['"]((?:G|AW|GT|DC)-[A-Z0-9-]{4,20})['"]/g, inline).forEach(function (id) { out.gtag.push({ id: id.replace(/\/.*$/, ''), via: 'gtag config' }); });
    all(/gtag\(\s*['"]event['"]\s*,\s*['"]conversion['"]\s*,\s*\{[^}]*send_to['"]?\s*:\s*['"](AW-\d+)/g, inline).forEach(function (id) { out.gtag.push({ id: id, via: 'conversion event' }); });

    // other vendors' pixels
    PIXELS.forEach(function (p) {
      var present = p[2].test(inline) || srcs.some(function (s) { return p[2].test(s); }); if (!present) return;
      var ids = [], x; p[1].lastIndex = 0; while ((x = p[1].exec(inline))) ids.push(x[1] || x[2]);
      if (p[0] === 'Klaviyo') srcs.forEach(function (s) { var k = /company_id=([A-Za-z0-9]{4,10})/.exec(s); if (k) ids.push(k[1]); });
      ids = uniq(ids.filter(Boolean));
      if (p[0] === 'Microsoft Ads' && !/bat\.bing\.com/.test(inline + srcs.join(' '))) return;
      (ids.length ? ids : [null]).forEach(function (id) { out.pixels.push({ vendor: p[0], id: id }); });
    });

    // retired Universal Analytics
    if (/google-analytics\.com\/(analytics|ga)\.js/.test(inline + ' ' + srcs.join(' '))) out.legacy.push({ vendor: 'Universal Analytics', id: (/(UA-\d{4,10}-\d{1,4})/.exec(inline) || [])[1] || null });

    // consent
    out.consent.defaults = (inline.match(/gtag\(\s*['"]consent['"]\s*,\s*['"]default['"]/g) || []).length + (inline.match(/['"]consent['"]\s*,\s*['"]default['"]/g) || []).length > 0 ? 1 : 0;
    out.consent.updates = /['"]consent['"]\s*,\s*['"]update['"]/.test(inline) ? 1 : 0;
    var cmpText = srcs.join(' ') + ' ' + inline.slice(0, 200000);
    out.consent.cmp = CMP.filter(function (c) { return c[0].test(cmpText); }).map(function (c) { return c[1]; });

    // dataLayer events pushed in the page source
    var ev = []; all(/dataLayer\.push\(\s*(\{[\s\S]{0,800}?\})\s*\)/g, inline).forEach(function (obj) { var e = /['"]?event['"]?\s*:\s*['"]([^'"]{1,80})['"]/.exec(obj); if (e) ev.push(e[1]); });
    out.events = uniq(ev.filter(function (e) { return !/^gtm\./.test(e); }));

    // server endpoints configured in source (gtag server_container_url / transport_url)
    out.endpoints = uniq(all(/(?:server_container_url|transport_url)['"]?\s*:\s*['"](https?:\/\/[^'"]+)['"]/g, inline).map(hostOf).filter(Boolean));

    out.platform = PLATFORM.filter(function (p) { return p[0].test(html.slice(0, 400000)); }).map(function (p) { return p[1]; });

    // links, for the crawl frontier
    var base = pageUrl, bh = /<base\b[^>]*href\s*=\s*["']([^"']+)["']/i.exec(html); if (bh) base = abs(bh[1]);
    var seen = {};
    all(/<a\b[^>]*?\bhref\s*=\s*["']([^"']+)["']/gi, html).forEach(function (h) {
      if (/^(mailto|tel|javascript|data):/i.test(h) || h.charAt(0) === '#') return;
      var n = normalize(h.replace(/&amp;/g, '&'), base); if (n && !seen[n]) { seen[n] = 1; out.links.push(n); }
    });
    out.links = out.links.slice(0, 400);

    // client-rendered pages carry almost no text in the source: the scan sees less of them
    out.textChars = html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/gi, ' ').replace(/\s+/g, ' ').trim().length;
    return out;
  }

  /* ---------- the whole site ---------- */
  function summarize(pages) {
    var ok = pages.filter(function (p) { return p.result; }), S = {
      pages: pages.length, ok: ok.length, failed: pages.length - ok.length,
      blocked: pages.filter(function (p) { return !p.result && /^(401|403|429|503)$/.test(String(p.http_status || '')); }).length,
      gtm: {}, loaders: {}, gtag: {}, pixels: {}, legacy: {}, events: {}, endpoints: {}, cmp: {}, platform: {},
      consentDefaultPages: 0, thinPages: 0, notInHead: {}, doubled: {}, urls: ok.map(function (p) { return p.final_url || p.url; }),
    };
    var bump = function (map, k, url) { if (!k) return; var e = map[k] = map[k] || { pages: 0, urls: [] }; e.pages++; if (e.urls.indexOf(url) < 0 && e.urls.length < 100) e.urls.push(url); };
    ok.forEach(function (p) {
      var r = p.result, url = p.final_url || p.url;
      var perId = {};
      var bodyOnly = {}; r.gtm.forEach(function (g) { var k = g.id || '(custom loader, ID not readable)'; perId[k] = (perId[k] || 0) + 1; if (bodyOnly[k] !== false) bodyOnly[k] = !g.head && r.inHead; });
      Object.keys(bodyOnly).forEach(function (k) { if (bodyOnly[k]) bump(S.notInHead, k, url); });
      Object.keys(perId).forEach(function (k) {
        var hosts = uniq(r.gtm.filter(function (g) { return (g.id || '(custom loader, ID not readable)') === k; }).map(function (g) { return g.host; }));
        bump(S.gtm, k, url); var e = S.gtm[k]; e.hosts = uniq((e.hosts || []).concat(hosts)); e.via = uniq((e.via || []).concat(r.gtm.filter(function (g) { return (g.id || '(custom loader, ID not readable)') === k; }).map(function (g) { return g.via; })));
        if (perId[k] > 1) bump(S.doubled, k, url);
      });
      r.loaders.forEach(function (l) { bump(S.loaders, l.host, url); });
      uniq(r.gtag.map(function (g) { return g.id; })).forEach(function (id) { bump(S.gtag, id, url); });
      uniq(r.pixels.map(function (x) { return x.vendor + '|' + (x.id || ''); })).forEach(function (k) { bump(S.pixels, k, url); });
      r.legacy.forEach(function (x) { bump(S.legacy, x.vendor + '|' + (x.id || ''), url); });
      r.events.forEach(function (e) { bump(S.events, e, url); });
      r.endpoints.forEach(function (h) { bump(S.endpoints, h, url); });
      r.consent.cmp.forEach(function (c) { bump(S.cmp, c, url); });
      r.platform.forEach(function (c) { bump(S.platform, c, url); });
      if (r.consent.defaults) S.consentDefaultPages++;
      if (r.textChars < 250) S.thinPages++;
    });
    return S;
  }

  /* ---------- live site vs the container export ---------- */
  function strings(v, out) { out = out || []; if (typeof v === 'string') out.push(v); else if (v && typeof v === 'object') Object.keys(v).forEach(function (k) { strings(v[k], out); }); return out; }
  function param(row, key) { var p = (row.parameter || []).filter(function (x) { return x.key === key; })[0]; return p ? p.value : undefined; }
  function listen(cv) {
    var evs = {}, regex = [];
    (cv.trigger || []).forEach(function (t) {
      if (t.type !== 'CUSTOM_EVENT') return;
      (t.customEventFilter || []).forEach(function (c) { var a = {}; (c.parameter || []).forEach(function (p) { a[p.key] = p.value; }); if (c.type === 'EQUALS' && a.arg1) evs[a.arg1] = t.name; else if (a.arg1) { try { regex.push([new RegExp(c.type === 'MATCH_REGEX' ? a.arg1 : a.arg1.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), /ignore_case/.test(JSON.stringify(c)) ? 'i' : ''), t.name]); } catch (e) { /* bad pattern */ } } });
    });
    return function (e) { if (evs[e]) return evs[e]; for (var i = 0; i < regex.length; i++) if (regex[i][0].test(e)) return regex[i][1]; return null; };
  }
  // Which tags in the export carry this ID (directly, or through a constant variable)?
  function tagsWithId(cv, id) {
    var bare = String(id).replace(/^AW-/, ''), tokenRe = new RegExp('(^|[^A-Za-z0-9])' + bare.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&') + '([^A-Za-z0-9]|$)');
    var consts = {}; (cv.variable || []).forEach(function (v) { if (strings(v.parameter || []).some(function (s) { return tokenRe.test(s); })) consts[v.name] = 1; });
    return (cv.tag || []).filter(function (t) {
      if (t.paused) return false;
      return strings(t.parameter || []).some(function (s) { return tokenRe.test(s) || Object.keys(consts).some(function (n) { return s.indexOf('{{' + n + '}}') >= 0; }); });
    });
  }
  function pagesText(e, total) { return e.pages === total ? 'every crawled page (' + total + ')' : e.pages + ' of ' + total + ' crawled pages'; }
  function egs(e) { return e.urls.slice(0, 3).map(function (u) { try { var x = new URL(u); return x.pathname + x.search; } catch (er) { return u; } }).join(', '); }

  // the tag that loads the base library (config / PageView) represents the duplicate; the rest are named in the count
  function lead(tags, type, name) { return tags.filter(function (t) { return name.test(t.name); })[0] || tags.filter(function (t) { return type.test(t.type); })[0] || tags[0]; }
  function others(tags) { return tags.length > 1 ? ' (' + (tags.length - 1) + ' more tag' + (tags.length > 2 ? 's use' : ' uses') + ' the same ID)' : ''; }
  function compare(S, web, server, site) {
    var items = [], cv = web ? web.cv : null, webId = web ? web.info.publicId : null, n = S.ok;
    var add = function (code, severity, name, message, tag, ref) {
      items.push({ tab: tag ? 0 : null, nodeId: tag ? 'tag:' + tag.tagId : null, container: 'Live site', context: 'site', severity: severity, check: 'Site scan', kind: tag ? 'tag' : 'site', ref: ref || (tag ? String(tag.tagId) : site), name: name, type: tag ? tag.type : 'page source', message: message, key: 'Live site|scan|' + code + '|' + (ref || '') + '|' + name });
    };
    if (!n) {
      add('unreadable', 'review', site, 'The scan could not read any page on ' + site + (S.blocked ? ': ' + S.blocked + ' requests were refused (bot protection or rate limiting).' : '.') + ' The live-site checks were skipped; the configuration audit is unaffected.');
      return items;
    }
    if (S.blocked) add('blocked', 'info', site, S.blocked + ' of ' + S.pages + ' pages refused the scanner (bot protection or rate limiting), so coverage is partial.');

    // 1. is this container installed, everywhere, once?
    var ids = Object.keys(S.gtm), unreadable = S.gtm['(custom loader, ID not readable)'];
    if (webId && cv) {
      var mine = S.gtm[webId];
      if (!mine && unreadable) add('gtm-custom', 'review', webId, webId + ' was not named in the page source, but a custom GTM loader from ' + unreadable.hosts.join(', ') + ' runs on ' + pagesText(unreadable, n) + '. Custom loaders hide the container ID, so confirm in GTM Preview that it is ' + webId + '.');
      else if (!mine) add('gtm-missing', 'critical', webId, webId + ' does not appear in the source of any of the ' + n + ' crawled pages. Either it is not installed, it is added by a plugin or app embed after load, or the site runs a different container' + (ids.length ? ' (' + ids.join(', ') + ' found instead)' : '') + '.');
      else if (mine.pages < n) {
        var p = function (u) { try { return new URL(u).pathname; } catch (e) { return u; } };
        var viaLoader = unreadable ? unreadable.urls : [], rest = S.urls.filter(function (u) { return mine.urls.indexOf(u) < 0; });
        var missing = rest.filter(function (u) { return viaLoader.indexOf(u) < 0; }), loaderOnly = rest.filter(function (u) { return viaLoader.indexOf(u) >= 0; });
        if (missing.length) add('gtm-partial', 'review', webId, webId + ' loads on ' + (n - missing.length) + ' of ' + n + ' crawled pages. Missing on ' + missing.slice(0, 4).map(p).join(', ') + (missing.length > 4 ? ' and ' + (missing.length - 4) + ' more' : '') + '. Pages without it send no tags at all, usually a separate template or landing-page builder.' + (loaderOnly.length ? ' ' + loaderOnly.length + ' more page' + (loaderOnly.length === 1 ? '' : 's') + ' load GTM through a custom loader whose container ID cannot be read.' : ''));
        if (loaderOnly.length) add('gtm-mixed', 'info', webId, loaderOnly.length + (loaderOnly.length === 1 ? ' page (' : ' pages (e.g. ') + '' + loaderOnly.slice(0, 3).map(p).join(', ') + ') ' + (loaderOnly.length === 1 ? 'loads' : 'load') + ' GTM through a custom loader from ' + unreadable.hosts.join(', ') + ' while others use the standard snippet. Confirm both load ' + webId + ', and use one install method everywhere.');
      }
      if (S.doubled[webId]) add('gtm-double', 'review', webId, webId + ' loads twice on ' + pagesText(S.doubled[webId], n) + ' (e.g. ' + egs(S.doubled[webId]) + '). GTM ignores a repeat of the same ID, but two snippets usually mean a plugin and a theme both install it; remove one before they diverge.');
      if (S.notInHead[webId]) add('gtm-body', 'info', webId, 'The ' + webId + ' snippet sits in <body>, not <head>, on ' + pagesText(S.notInHead[webId], n) + '. Tags start later, and visitors who leave quickly are not counted.');
      if (mine) {
        var fp = mine.hosts.filter(function (h) { return rootDomain(h) === site; }), google = mine.hosts.filter(function (h) { return GOOGLE_HOST.test(h); }), third = mine.hosts.filter(function (h) { return !GOOGLE_HOST.test(h) && rootDomain(h) !== site; });
        var hasServer = !!server || strings(cv.tag || []).some(function (s) { return /server_container_url|transport_url/.test(s); }) || (cv.tag || []).some(function (t) { return /^https?:\/\//.test(String(param(t, 'server_container_url') || param(t, 'transportUrl') || '')); });
        if (third.length) add('loader-3p', 'review', webId, 'GTM is served from ' + third.join(', ') + ', which is not on ' + site + '. A loader on a third-party domain gets blocked like googletagmanager.com does; serve it from a subdomain of ' + site + '.');
        else if (google.length && !fp.length && hasServer) add('loader-google', 'info', webId, 'This setup has a server container, but gtm.js still loads from ' + google[0] + '. Serving it from the sGTM subdomain (a custom loader) makes it first-party, so ad blockers and browser tracking protection stop fewer pages.');
      }
    }
    ids.filter(function (id) { return id !== webId && id.charAt(0) !== '('; }).forEach(function (id) {
      var e = S.gtm[id];
      add('gtm-other', 'review', id, 'A second container, ' + id + ', loads on ' + pagesText(e, n) + ' (e.g. ' + egs(e) + '). It is outside this audit: its tags are not checked here and can send the same events again. Export it and audit it too, or remove it.');
    });

    // 2. tags hard-coded in the page source
    Object.keys(S.gtag).forEach(function (id) {
      var e = S.gtag[id], tags = cv ? tagsWithId(cv, id) : [], ga = /^G-/.test(id);
      if (tags.length) { var t = lead(tags, /^googtag$|^gaawc$|^sp$/, /config|base|all pages|page ?view|remarketing/i); add('dup-' + id, ga ? 'critical' : 'review', t.name, id + ' is hard-coded in the page source (gtag.js) on ' + pagesText(e, n) + ' and is also loaded by GTM tag "' + t.name + '"' + others(tags) + '. ' + (ga ? 'Both send page views, so GA4 counts every page twice.' : 'Conversions and remarketing can fire twice; keep one of the two.'), t, id); }
      else add('hard-' + id, 'review', id, id + ' is hard-coded in the page source (gtag.js) on ' + pagesText(e, n) + ', outside GTM. This container does not use it, so this audit does not cover it. Move it into GTM or confirm who owns it.');
    });
    Object.keys(S.pixels).forEach(function (k) {
      var e = S.pixels[k], vendor = k.split('|')[0], id = k.split('|')[1], tags = cv && id ? tagsWithId(cv, id) : [];
      if (tags.length) { var t = lead(tags, /^html$/, /base|page ?view|all pages|insight/i); add('dup-' + k, /Meta|TikTok|Pinterest|Snapchat|Reddit/.test(vendor) ? 'critical' : 'review', t.name, vendor + ' ' + id + ' is initialised in the page source on ' + pagesText(e, n) + ' and again by GTM tag "' + t.name + '"' + others(tags) + '. The platform counts the page view twice unless both send the same event ID.', t, id); }
      else add('hard-' + k, /Hotjar|Clarity|Klaviyo|Segment/.test(vendor) ? 'info' : 'review', vendor + (id ? ' ' + id : ''), vendor + (id ? ' ' + id : '') + ' runs from the page source on ' + pagesText(e, n) + ', outside GTM. ' + (cv ? 'This container has no tag for it, so changes to it are not visible in GTM.' : ''));
    });
    Object.keys(S.legacy).forEach(function (k) { var e = S.legacy[k]; add('legacy-' + k, 'review', 'Universal Analytics' + (k.split('|')[1] ? ' ' + k.split('|')[1] : ''), 'analytics.js (Universal Analytics) still loads from the page source on ' + pagesText(e, n) + '. Google stopped processing UA data in July 2023: it sends nothing useful and slows the page. Remove it.'); });

    // 3. dataLayer events in the source that no trigger listens for
    if (cv) {
      var heard = listen(cv), deaf = Object.keys(S.events).filter(function (e) { return !heard(e); });
      deaf.forEach(function (ev) { var e = S.events[ev]; add('event-' + ev, 'review', ev, 'The site pushes "' + ev + '" to the dataLayer on ' + pagesText(e, n) + ' (e.g. ' + egs(e) + '), but no Custom Event trigger in ' + webId + ' listens for it, so nothing is sent.'); });
    }

    // 4. consent
    var cmps = Object.keys(S.cmp);
    if (cv) {
      var consentInit = (cv.tag || []).some(function (t) { return !t.paused && ((t.firingTriggerId || []).map(String).indexOf('2147479572') >= 0 || /consent/i.test(t.name) || /consent/i.test(String(t.type))); });
      if (cmps.length && !S.consentDefaultPages && !consentInit) add('consent', 'review', cmps.join(', '), cmps.join(', ') + ' runs on the site, but no Consent Mode default is set in the page source and no tag in ' + webId + ' fires on Consent Initialization. Google tags start without a consent state, so they either ignore the banner or lose modelled conversions.');
      else if (!cmps.length && !S.consentDefaultPages && !consentInit) add('consent-none', 'info', site, 'No consent banner and no Consent Mode default were found in the page source or the container. If this site gets visitors from the EEA, UK or states with opt-out laws, that is a compliance gap. Banners loaded by GTM itself are not visible to this check.');
    }

    // 5. server endpoints configured in the source
    Object.keys(S.endpoints).forEach(function (h) { if (rootDomain(h) !== site) add('endpoint-' + h, 'review', h, 'The page source sends Google tags to ' + h + ', which is not on ' + site + '. A server endpoint on another domain is third-party: its cookies are short-lived in Safari and it is easy to block.'); });

    if (S.thinPages && S.thinPages >= Math.ceil(n / 2)) add('thin', 'info', site, S.thinPages + ' of ' + n + ' pages arrive with almost no content in the source: the site renders in the browser. Tags and dataLayer pushes added by its JavaScript are not visible to a source scan; the rendered scan (next phase) covers them.');
    return items;
  }

  // a short summary that rides along in the report
  function brief(S, web) {
    var webId = web ? web.info.publicId : null, mine = webId && S.gtm[webId];
    return {
      pages: S.pages, ok: S.ok, blocked: S.blocked,
      coverage: mine ? mine.pages : 0, loaders: mine ? mine.hosts : [],
      containers: Object.keys(S.gtm).map(function (k) { return { id: k, pages: S.gtm[k].pages, hosts: S.gtm[k].hosts }; }),
      hardcoded: Object.keys(S.gtag).map(function (k) { return { vendor: /^G-/.test(k) ? 'Google Analytics 4' : /^AW-/.test(k) ? 'Google Ads' : 'Google tag', id: k, pages: S.gtag[k].pages }; })
        .concat(Object.keys(S.pixels).map(function (k) { return { vendor: k.split('|')[0], id: k.split('|')[1] || '', pages: S.pixels[k].pages }; }))
        .concat(Object.keys(S.legacy).map(function (k) { return { vendor: 'Universal Analytics', id: k.split('|')[1] || '', pages: S.legacy[k].pages }; })),
      events: Object.keys(S.events), cmp: Object.keys(S.cmp), consentDefaultPages: S.consentDefaultPages, platform: Object.keys(S.platform), urls: S.urls,
    };
  }

  return { detect: detect, summarize: summarize, compare: compare, brief: brief, robots: robots, allowed: allowed, sitemapLocs: sitemapLocs, sample: sample, template: template, normalize: normalize, crawlable: crawlable, rootDomain: rootDomain, hostOf: hostOf };
})();
export default GTM_SCAN;
