import {createSupabaseMcpForTesting} from 'npm:chumbo@0.11.0/testing';
import {registerCapabilities} from '../supabase/functions/gtm-autoresearch/capabilities.ts';
import {createApp,withCors} from '../supabase/functions/gtm-autoresearch/index.ts';
const assert=(v:unknown,msg='Assertion failed')=>{if(!v)throw Error(msg)};
const fixture=JSON.parse(await Deno.readTextFile(new URL('../../../tests/fixtures/container.json',import.meta.url)));
Deno.env.set('SUPABASE_URL','https://fixture.supabase.co');Deno.env.set('SUPABASE_ANON_KEY','test-only-public-placeholder');
Deno.test('Real Chumbo transport scores, compares, persists owner evidence and rejects forged access',async()=>{
 const rows:any[]=[];
 function client(owner:string){return {from(table:string){let filters:any[]=[],insert:any=null,one=false,limit=100;const q:any={insert(v:any){insert=v;return q},select(){return q},eq(k:string,v:unknown){filters.push((r:any)=>r[k]===v);return q},gt(k:string,v:number){filters.push((r:any)=>r[k]>v);return q},order(){return q},limit(v:number){limit=v;return q},maybeSingle(){one=true;return q},then(resolve:any){if(table==='skill_loop_history'&&insert){rows.push({...insert,owner_id:owner,sequence:rows.length+1,saved_at:new Date().toISOString()});return Promise.resolve({data:null,error:null}).then(resolve);}const data=table==='skill_loop_history'?rows.filter(r=>r.owner_id===owner&&filters.every(fn=>fn(r))).slice(0,limit):[];return Promise.resolve({data:one?(data[0]??null):data,error:null}).then(resolve);}};return q;}};}
 const app=createSupabaseMcpForTesting({server:{name:'GTM test',version:'0.1.0'},resourceUrl:new URL('https://fixture.supabase.co/functions/v1/gtm-autoresearch'),auth:{mode:'oauth',scopes:['openid','email']},access:{resolveScopes:()=>['history:read','history:write','review:decide']},register:registerCapabilities},{verifyToken:async(token:string)=>{if(!['alice','bob'].includes(token))throw Error('Rejected');return {token,userClaims:{id:token,role:'authenticated'},jwtClaims:{sub:token,exp:Date.now()/1000+3600}}},createClient:(token:any)=>client(token) as any,createAdminClient:()=>{throw Error('No admin client permitted')},fetch:async()=>Response.json({issuer:'https://fixture.supabase.co/auth/v1',authorization_endpoint:'https://fixture.supabase.co/auth/v1/oauth/authorize',token_endpoint:'https://fixture.supabase.co/auth/v1/oauth/token',registration_endpoint:'https://fixture.supabase.co/auth/v1/oauth/register'}),randomUUID:()=>crypto.randomUUID()});
 async function rpc(owner:string,method:string,params:any){const response=await app.fetch(new Request('https://fixture.supabase.co/functions/v1/gtm-autoresearch',{method:'POST',headers:{Authorization:'Bearer '+owner,'content-type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method,params})}));assert(response.ok,'HTTP failed');const raw=await response.text(),body=response.headers.get('content-type')?.includes('text/event-stream')?JSON.parse(raw.split('\n').filter(x=>x.startsWith('data: ')).at(-1)!.slice(6)):JSON.parse(raw);if(body.error)throw Error(body.error.message);return body.result;}
 async function call(owner:string,name:string,args:any){const r=await rpc(owner,'tools/call',{name,arguments:args});if(r.isError)throw Error(r.content?.[0]?.text);return r.structuredContent;}
 try{
  for(const owner of ['alice','bob'])await rpc(owner,'initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'test',version:'1'}});
  const first=await call('alice','evaluate_gtm_container',{project:'workshop',containerName:'demo',container:fixture});assert(first.qa.status==='recomputed-gtm-evidence');assert(rows.length===1);const id=first.record.id;
  const candidate=structuredClone(fixture);candidate.containerVersion.tag[0].name='GA4 - purchase';
  const second=await call('alice','compare_gtm_candidate',{baselineId:id,candidate});assert(second.qa.comparison.eligible);assert(second.qa.comparison.applied===false);assert(second.record.document.payload.parentId===id);assert(rows[0].document.payload.container.containerVersion.tag[0].name==='purchase tag');assert(second.record.document.payload.snapshotHash===first.record.document.payload.snapshotHash);
  const bad=structuredClone(candidate);bad.containerVersion.tag[0].firingTriggerId=['missing'];const rejected=await call('alice','compare_gtm_candidate',{baselineId:id,candidate:bad});assert(!rejected.qa.comparison.eligible);
  let blocked=false;try{await call('alice','compare_gtm_candidate',{baselineId:rejected.record.id,candidate});}catch{blocked=true;}assert(blocked,'Rejected proposal became baseline');
  const history=await call('alice','open_skill_history',{project:'workshop',skillId:'demo'});assert(history.events.length===3);
  assert((await call('bob','open_skill_history',{project:'workshop',skillId:'demo'})).events.length===0);
  for(const name of ['compare_gtm_candidate','get_history_record']){let denied=false;try{await call('bob',name,name==='get_history_record'?{id}:{baselineId:id,candidate});}catch{denied=true;}assert(denied,'Cross-user access');}
  let malformed=false;try{await call('alice','evaluate_gtm_container',{project:'workshop',containerName:'demo',container:{}});}catch{malformed=true;}assert(malformed);assert(rows.length===3,'Malformed input was saved');
  const tools=await rpc('alice','tools/list',{});assert(!tools.tools.some((x:any)=>x.name==='save_history_record'),'Untrusted generic record upload enabled');
  const resources=await rpc('alice','resources/list',{});assert(resources.resources.some((x:any)=>x.uri.includes('gtm-autoresearch-history')));
 }finally{await app.close();}
});
Deno.test('OAuth challenge and restricted CORS',async()=>{const app=createApp('https://fixture.supabase.co'),handler=withCors(app);try{const response=await handler(new Request('https://fixture.supabase.co/functions/v1/gtm-autoresearch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list',params:{}})}));assert(response.status===401);assert(response.headers.get('www-authenticate')?.includes('resource_metadata='));assert((await handler(new Request('https://fixture.supabase.co/functions/v1/gtm-autoresearch',{method:'OPTIONS',headers:{Origin:'https://evil.example'}}))).status===403);}finally{await app.close();}});
