import {createAppWorkspace} from 'chumbo/app';
import './style.css';
const root=document.getElementById('workspace'),$=id=>document.getElementById(id);
const workspace=createAppWorkspace({name:'GTM Autoresearch · Organized AI',version:'0.1.0'},{root});
const {app}=workspace;let query=null,next=null,busy=false;
const text=(tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;};
const button=(label,fn,cls)=>{const el=text('button',label,cls);el.type='button';el.onclick=fn;return el;};
const percentage=n=>Number.isFinite(n)?(n*100).toFixed(1)+'%':'Unavailable';
function message(value){$('notice').textContent=value;}
function payload(result){if(result.isError)throw Error(result.content?.find(c=>c.type==='text')?.text??'Operation failed');if(!result.structuredContent)throw Error('No structured result');return result.structuredContent;}
async function call(name,args){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);message('');try{const value=payload(await app.callServerTool({name,arguments:args}));render(value);return value;}catch(e){message(e.message+' No GTM changes were made.');}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function disclosure(label,value){const el=document.createElement('details');el.append(text('summary',label),text('pre',typeof value==='string'?value:JSON.stringify(value,null,2)));return el;}
function render(data){if(data.record){query={project:data.record.document.project,skillId:data.record.document.skillId,after:0};renderDetail(data);return;}if(!Array.isArray(data.events))throw Error('Unexpected history response');query={project:data.project,skillId:data.skillId,after:0};next=data.next;$('context').textContent=`${data.project} / ${data.skillId} · inspect a record before comparing scores across different inputs`;$('history').replaceChildren();$('more').hidden=next===null;if(!data.events.length)$('history').append(text('p','No saved runs yet.'));for(const row of data.events){const card=text('article','','run'),description=text('div','');description.append(text('small',new Date(row.saved_at).toLocaleString()),text('h2',row.kind==='proposal'?'Proposed revision':'Baseline'),text('p',`${Number.isFinite(row.summary?.score)?row.summary.score.toFixed(1)+'%':'No score'} · historical reported score`));card.append(description,button('Open separate QA report',()=>call('get_history_record',{id:row.record_hash})));$('history').append(card);}}
function renderDetail(data){const target=$('detail');target.hidden=false;target.replaceChildren();const d=data.record.document,p=d.payload,qa=data.qa;const verified=qa.status==='recomputed-gtm-evidence',result=verified?qa.result:null,comparison=verified?qa.comparison:null;
 $('context').textContent=`${d.project} / ${d.skillId} · ${new Date(d.occurredAt).toLocaleString()}`;
 target.append(text('h2',d.kind==='proposal'?'Two versions. Separate evidence.':'Your container. Clear evidence.'),text('p',qa.scope??qa.reason,'dim'));
 const metrics=text('div','','metrics');for(const [label,value]of [['Heuristic score',result?percentage(result.combinedScore):'Not verified'],['Dimensions',result?.dimensions.length??'—'],['Findings',result?.issues.length??'—'],['Review status',comparison?.status??'Baseline only']]){const card=text('article','');card.append(text('small',label),text('strong',String(value)));metrics.append(card);}target.append(metrics);
 if(comparison){target.append(text('p',`Baseline ${percentage(comparison.before.combinedScore)} → candidate ${percentage(comparison.after.combinedScore)}. ${comparison.meaning}`));if(comparison.reasons.length)target.append(disclosure('Why this candidate is not eligible',comparison.reasons));}
 if(result){const table=document.createElement('table');const head=document.createElement('tr');for(const value of ['Dimension','Baseline','Candidate / current','Weight'])head.append(text('th',value));const thead=document.createElement('thead');thead.append(head);table.append(thead);const body=document.createElement('tbody');for(const dim of result.dimensions){const tr=document.createElement('tr');for(const value of [dim.name,comparison?percentage(comparison.before.dimensions.find(x=>x.name===dim.name)?.score):'—',percentage(dim.score),String(dim.weight)])tr.append(text('td',value));body.append(tr);}table.append(body);target.append(table);}
 const cases=text('div','','cases');for(const [label,value]of p.original?[['Baseline export',p.original],['Proposed export',p.container]]:[['Evaluated export',p.container]]){const card=text('article','');card.append(text('h3',label),disclosure('Inspect complete JSON',value));cases.append(card);}target.append(cases,disclosure('Shared ads snapshot and evidence identities',{snapshot:p.snapshot??'No ads data supplied; structural checks only',containerHash:p.containerHash,snapshotHash:p.snapshotHash,engineDigest:p.engineDigest,parentId:p.parentId??null}));
 target.append(text('h2','Evaluator findings'),text('p','Save a finding for review to accept it, dismiss it with a reason, or reopen it. Decisions do not change scores.','dim'));
 for(const [i,issue]of (result?.issues??[]).entries()){const row=document.createElement('details');row.append(text('summary',`${issue.severity} · ${issue.dimension} · ${issue.entity}`),text('p',issue.message));const key='evaluator-'+i;const saved=data.findings.find(f=>f.finding_key===key);if(!saved){row.append(button('Save for review',async()=>{if(busy)return;busy=true;try{payload(await app.callServerTool({name:'add_review_finding',arguments:{recordId:data.record.id,key,finding:`${issue.dimension} · ${issue.entity}: ${issue.message}`}}));}catch(e){message(e.message);}finally{busy=false;}await call('get_history_record',{id:data.record.id});}));}else row.append(text('small','Saved below · '+saved.status));target.append(row);}
 target.append(text('h2','Your review decisions'));
 if(!data.findings.length)target.append(text('p','No decisions recorded.'));
 for(const finding of data.findings){const row=text('article',''),note=document.createElement('textarea');note.maxLength=4000;note.value=finding.note;note.id='note-'+finding.id;const label=text('label','Reason or next action');label.htmlFor=note.id;row.append(text('small',finding.status),text('p',finding.finding),label,note);const actions=text('div','','actions');for(const [status,title]of [['accepted','Accept finding'],['dismissed','Dismiss finding'],['pending','Reopen']])actions.append(button(title,()=>{if(status==='dismissed'&&!note.value.trim()){message('Add a reason before dismissing.');note.focus();return;}call('decide_review_finding',{id:finding.id,revision:finding.revision,status,note:note.value.trim()});},status==='accepted'?'primary':''));row.append(actions);target.append(row);}
 target.append(text('p','Ask Claude to propose another complete candidate using this saved evidence. Each candidate is tested again; nothing here imports or publishes to GTM.','dim'),button('Download evidence',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gtm-autoresearch-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));}
$('refresh').onclick=()=>query?call('refresh_skill_history',query):message('Ask Claude to open history for your project and container.');$('more').onclick=()=>query&&next!==null&&call('refresh_skill_history',{...query,after:next});app.ontoolresult=result=>{try{render(payload(result));}catch(e){message(e.message);}};app.onerror=()=>message('Connection lost. Reopen GTM Autoresearch to reconnect.');await workspace.connect();
